# Generated by Django 3.2 on 2022-06-20 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_stock_qty'),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='products',
        ),
        migrations.AddField(
            model_name='favourites',
            name='products',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='products.product'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='username',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='product_favourites',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
