# Generated by Django 3.2 on 2022-07-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='optin',
            field=models.IntegerField(choices=[(0, 'null'), (1, 'Optout'), (2, 'Optin')], default=0),
        ),
    ]
