# Generated by Django 3.2 on 2022-07-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20220703_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='optin',
            field=models.IntegerField(choices=[(0, 'Choose:'), (1, 'Optout'),
                                               (2, 'Optin')],
                                      default=2),
        ),
    ]
