# Generated by Django 3.2 on 2022-07-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_optin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='optin',
            field=models.IntegerField(choices=[(0, 'Optin'), (1, 'Optout'), (2, 'Delete:')]),
        ),
    ]
