# Generated by Django 3.2 on 2022-07-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productreviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='excerpt',
            new_name='summary',
        ),
    ]
