# Generated by Django 3.2 on 2022-07-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productreviews', '0002_rename_excerpt_productreview_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
