# Generated by Django 3.2 on 2022-06-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220622_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='category',
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts_topic', to='forum.forumtopics'),
        ),
    ]
