# Generated by Django 3.2 on 2022-06-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20220623_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopics',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
