# Generated by Django 3.2 on 2022-06-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forumtopics_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='forumtopics',
            name='slug',
            field=models.SlugField(default=2, max_length=200),
        ),
    ]
