# Generated by Django 3.2 on 2022-06-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20220623_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(max_length=199, unique=True),
        ),
    ]
