# Generated by Django 3.2 on 2022-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220518_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
